[package]
name = "telegram"
version = "0.1.0-pre"
description = "Unofficial Telegram API Library"
authors = ["Ryan Leckey <leckey.ryan@gmail.com>"]

[dependencies]
byteorder = "1.0.0"
error-chain = "0.9.0"
serde = "0.9.7"
serde_derive = "0.9.7"
telegram_codegen = { path = "./telegram_codegen" }
