[package]
name = "create_auth_key"
version = "0.0.0"
workspace = "../../"

[dependencies]
env_logger = "0.4.3"
extprim = "1.4.0"
extprim_literals = "2.0.3"
futures = "0.1"
hyper = "0.11"
log = "0.3.8"
telegram = { path = "../../telegram" }
tokio-core = "0.1"
