[package]
name = "create_auth_key"
version = "0.0.0"
workspace = "../../"

[dependencies]
extprim = "1.4.0"
extprim_literals = "2.0.3"
futures = "0.1"
hyper = "0.11"
serde_mtproto = "0.1.0"
telegram = { path = "../../telegram" }
tokio-core = "0.1"
